### ISSUE TITLE
Build on Mac not successfull

### ISSUE THREAD

**Issue by Schedulaar** [aeirola/react-native-svg-asset-plugin#11]
First, thanks for your library!
When building our app for iPhone in a Mac environment, the images are not rendered (the build doesn't cancel though).

The console gives the following output: 
 ```Loading dependency graph, done.
bundle: Writing bundle output to: /[...]/Build/Intermediates.noindex/ArchiveIntermediates/Integreat/BuildProductsPath/Release-iphoneos/Integreat.app/main.jsbundle
bundle: Done writing bundle output

Input buffer has corrupt header: glib: SVG has no elements



Error: Input buffer has corrupt header: glib: SVG has no elements



+ [[ false != true ]]
+ [[ ! -f /[...]/Build/Intermediates.noindex/ArchiveIntermediates/Integreat/BuildProductsPath/Release-iphoneos/Integreat.app/main.jsbundle ]]
```

A similar library like yours uses a workaround for this issue:
https://github.com/aeirola/react-native-icon-builder/commit/c1e8262f818f47f30389b18054022f8818131bbc

This issue might also be related to https://github.com/lovell/sharp/issues/1593.

I hope you can fix this.

Edit: I just noticed this other library is authored by you as well :D Do you think this is the same issue here?

Edit2: I just saw that you already released something 3 hours ago for this :O I'm checking this out :heart

Edit3: It does already work, thanks :+1:

**Comment by aeirola** [comment]
Yeah, I was having the exact same issues. Seems like the probability of the error appearing increased lately. Now fixed with a workaround on both repos, I'll remove the workaround once the underlying issue is fixed in sharp.

Thanks for your interest in the plugin. react-native-icon-builder is indeed an older project I've done, which is now being replaced by this plugin, and separate tool for building app icons which is still under work though.
