### ISSUE TITLE
PNG compression

### ISSUE THREAD

**Issue by Schedulaar** [aeirola/react-native-svg-asset-plugin#14]
It would be nice if the generated pngs could be compressed, for example by using pngquant, to reduce the file size of the pngs.
It would be cool if this could be configurable.

**Comment by aeirola** [comment]
Sounds like you are facing some issues with large PNG results. One simple way to reduce file sizes of simple single-color icons is to change the colors to black, and then use React Native `tintColor` style to set the desired color during runtime.

The PNGs are already losslessly compressed with zlib compression provided by sharp (https://sharp.pixelplumbing.com/en/stable/api-output/#png). So I guess you are talking about lossy compression by reducing the number of colors in the resulting PNG. Sharp does expose some configuration for libimagequant, although it requires libvips to be compiled with support for it. I guess it could be feasible to expose the sharp configuration options through some configuration file for react-native-svg-asset-plugin.

I don't expect lossy compression to be a widely needed feature, so I'm a bit hesitant to add any extra dependencies, such as https://github.com/imagemin/pngquant-bin, to the package.

**Comment by aeirola** [comment]
I released version 0.2.0 which adds support for configuring the sharp PNG output options. This can be used to add pngquant compression of the output images.

If this isn't feasible in your specific case, possibly due to the specific compilation of libvips, I would consider a separate PNG compression asset plugin a better path, rather than adding more responsibilities to this one.

**Comment by Schedulaar** [comment]
This sounds like a very good compromise! Thanks!
